move ViolationHandler to common
chipsalliance/verible pull request #1080
Opened 2021-11-02 17:50 UTC by wsipak

This is a refactoring step before introducing Reviewdog Diagnostic Format in Verible:
https://github.com/chipsalliance/verible/pull/1018

`ViolationHandler` is the interface which is supposed to be implemented by `ViolationPrinter`, RDFormat printer, and other potential handlers.
This isn't specific to Verilog and thus we place it in `common`.

2021-11-02 20:14 UTC, hzeller requested changes
LGTM!
Just one missing dependency.

2021-11-02 20:14 UTC, hzeller commented on verilog/analysis/BUILD
> +        "//common/analysis:violation_handler",
I think the `verilog_linter_test` below also needs this dependency now.

2021-11-02 20:14 UTC, hzeller commented on verilog/analysis/verilog_linter_test.cc
> +#include "common/analysis/violation_handler.h"
... because of this added include.

2021-11-08 12:45 UTC, hzeller commented
If you add the dependency, this can be merged.

2021-11-08 18:08 UTC, wsipak commented
Now `verilog_linter_test` has `"//common/analysis:violation_handler"` as a dependency. Thank you.

2021-11-09 08:08 UTC, hzeller commented
LGTM!

2021-11-09 08:08 UTC, merged