Auto-generate waiver file from existing lint rules violations
chipsalliance/verible pull request #1297
Opened 2022-03-28 12:47 UTC by karimtera

This PR introduces:
A new feature for the linter, oringially proposed in [#1180](https://github.com/chipsalliance/verible/issues/1180)

Feature description:
Using the linter on big files usually outputs huge number of violations, this feature helps maintaining these violations.

Implementation:
New linter flag `--generate_auto_waiver <path_to_a_file> ` which writes the violations into a text file with waiver syntax, that is directly usable by flag `--waiver_files`
The new flag is by default not working, unless a path to a file is passed to it.
Generated waiver syntax follows the following:
`waive --rule=<rule_name> --line=<number> --location=<file_name>`

Use model:
A user have 'big_file.sv' that contains a lot of violations.
He can do the following:
`verible-verilog-lint big_file.sv --generate_auto_waiver violations.waiver`

Then, he can look into the generated violations, comment out some, leave some, and work his way to solve them.

`verible-verilog-lint big_file.sv --waiver_files violations.waiver`

He can also use both flags together, to check if there are new violations

`verible-verilog-lint big_file.sv --waiver_files violations.waiver --generate_auto_waiver new.waiver`

Fixes: [#1180](https://github.com/chipsalliance/verible/issues/1180)

2022-03-28 16:58 UTC, mglb requested changes

2022-03-30 12:06 UTC, mglb requested changes
Nice! Mostly cosmetic issues this time.

Please update [README.md](https://github.com/chipsalliance/verible/tree/master/verilog/tools/lint#external-waiver-files) to let people know about your feature!
- Add a short note telling that the waiver file can be generated using (COMMAND) at the end of [External waiver files](https://github.com/chipsalliance/verible/tree/master/verilog/tools/lint#external-waiver-files)
- Update the table in [Automatically fixing trivial violations](https://github.com/chipsalliance/verible/tree/master/verilog/tools/lint#automatically-fixing-trivial-violations), and change *"patch"* in *"If --autofix_output_file is not given, **patch** output is written to stdout."* to *"patch or waiver"*.
- Update [Usage](https://github.com/chipsalliance/verible/tree/master/verilog/tools/lint#usage) (just do copy-paste from `verible-verilog-lint --helpfull`)

2022-03-30 19:42 UTC, karimtera commented
Thanks a lot for your review :)

2022-04-01 11:27 UTC, mglb approved these changes
For completeness please add an entry for "generate-waiver" to a table in [README.md "Automatically fixing trivial violations" section](https://github.com/chipsalliance/verible/blob/aec56ff69188b71ce2985bac765dc33dc0a09536/verilog/tools/lint/README.md#automatically-fixing-trivial-violations), and fix formatting described in a comment.

After that it can be merged.

2022-04-01 11:27 UTC, mglb commented on verilog/tools/lint/README.md
> +Generated waiving rules will follow this format:
The command here is a bit long and it wraps. Let's format this similarly to [Rule configuration](https://github.com/chipsalliance/verible/blob/aec56ff69188b71ce2985bac765dc33dc0a09536/verilog/tools/lint/README.md#rule-configuration) section:


~~~
These waiver rules can be automatically generated with the AutoFix mode `generate-waiver` to stdout,
or to a waiver file if a path is passed to `--autofix_output_file`.

```bash
verible-verilog-lint --autofix=generate-waiver --autofix_output_file=violations.waiver ...
```

Generated waiving rules will follow this format:
~~~

2022-04-01 22:21 UTC, merged

2022-04-01 22:21 UTC, hzeller commented
Nice.
Thanks, merged!