Enable C++20 Support
chipsalliance/verible pull request #1428
Opened 2022-09-08 09:48 UTC by sschaetz

This change-set enables compilation of all of verible targets with C++20 support. Integration of verible into a C++20 enabled repo motivated this change.

There are 2 main depredations that this change-set remedies:
1. The deprecation of `std::iterator` (a good summary of what is going on can be found [here](https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/)) - this prompted the change in `common/util/expandable_tree_view.h`
2. The deprecation of support for aggregate initialization for types with user-declared constructors (prompted by [P1008](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1008r1.pdf)); a good explanation of the situation can be found in [this stackoverflow question](https://stackoverflow.com/questions/57271400/why-does-aggregate-initialization-not-work-anymore-since-c20-if-a-constructor).
  This change-set works around this change by adding constructors to the types in question. I don't think this is the only solution; I believe one could also try to remove the user-declared constructors but I'm not 100% sure this would work for all types.

I'm happy to address any comments including trying to solve (2.) in a different manner if what is proposed here is not a good path forward.

2022-09-08 15:47 UTC, sschaetz commented
Mhh, I'm not exactly sure why ClangTidy complains about things I did not change. Could this be the first time ClangTidy runs on these files?

2022-09-08 18:24 UTC, karimtera commented
> Mhh, I'm not exactly sure why ClangTidy complains about things I did not change. Could this be the first time ClangTidy runs on these files?

No, it is not the first time.
A lot of errors are in glog, maybe related to #1427, not sure about the other issues.

I am also getting similar issues in vim, that some glog headers are missing.

2022-09-08 18:41 UTC, hzeller requested changes
I think instead of adding a constructor, suggest to remove the other ones (copy/move).

That way, we can keep the improved readability with the aggregate construction.

2022-09-08 18:41 UTC, hzeller commented on .bazelrc
> -common:macos --features=-supports_dynamic_linker --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --client_env=BAZEL_CXXOPTS=-std=c++17
I would _not_ choose c++20 right now here, as we still want to have the code compatible with c++17 for people on older platforms with older compilers.

2022-09-08 18:41 UTC, hzeller commented on common/formatting/layout_optimizer_internal.h
> +  LayoutFunctionSegment(int column, const LayoutTree& layout, int span,
If we just remove he constructors below, we should not need this workaround (the constructors below are just default copy and move)

2022-09-08 18:41 UTC, hzeller commented on verilog/analysis/symbol_table.h
> +  ReferenceComponent(
If we just remove he constructors below, we should not need this workaround (the constructors below are just default copy and move)

2022-09-08 18:43 UTC, hzeller commented
Let's not worry about the clang-tidy problem for now, it indeed seems to be related to glog that has been updated recently.

This PR fixes #1400

2022-09-12 17:52 UTC, hzeller commented
I've disabled `clang-tidy` run for now, so if you re-base, this will not be in the way anymore.

2022-09-13 18:25 UTC, hzeller commented
Is there anything else you need to proceed @sschaetz ?

2022-09-13 21:53 UTC, hzeller commented
(I'll start putting the necessary changes in separate PRs)

2022-09-13 22:29 UTC, sschaetz commented
@hzeller apologies, I'm not abandoning this, just got busy with other stuff. Great if you can take it over though!

2022-09-13 22:58 UTC, hzeller commented
I started a pull request with the constructor issue #1451, if you want to have a quick review.

I'll then leave the iterator issue to you (good to fix, but we also need to make sure it keeps compiling with C++17)

2022-09-19 07:24 UTC, hzeller commented
Since this PR is implemented with two separate PRs #1451 and #1463, I'll close this now.

2022-09-19 07:24 UTC, closed without merging